### ISSUE TITLE
Automatic Documentation Generation

### ISSUE THREAD

**Issue by peasant98** [HIRO-group/hiro_ros_arm_controller#1]
As a convenience, this would be nice.

**Comment by a-nooj** [comment]
You planning to use sphinx?

**Comment by watakandai** [comment]
yes. It's already automated in `ros_robotic_skin` so we just have to copy & paste it. Feel free to do so.

**Comment by peasant98** [comment]
This is done - check out http://hiro-group.ronc.one/hiro_ros_arm_controller/
